name: publish

on: 
  push:
    tags:
      - v*.*.*

jobs:
  # goreleaser:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Go
  #       uses: actions/setup-go@v2
  #       with: 
  #         go-version: 1.15
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ secrets.CR_USER }}
  #         password: ${{ secrets.CR_PAT }}
  #     - name: GoReleaser
  #       uses: goreleaser/goreleaser-action@v2
  #       with: 
  #         version: latest
  #         args: release --rm-dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  helm-char:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
      - name: Helm Chart
        uses: liatrio/github-actions/helm-push@helm
        with:
          chart: helm/grafeas
          bucket: liatrio-helm