name: publish

on: 
  push:
    tags:
      - v*.*.*

jobs:
  # goreleaser:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Go
  #       uses: actions/setup-go@v2
  #       with: 
  #         go-version: 1.15
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ secrets.CR_USER }}
  #         password: ${{ secrets.CR_PAT }}
  #     - name: GoReleaser
  #       uses: goreleaser/goreleaser-action@v2
  #       with: 
  #         version: latest
  #         args: release --rm-dist
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: gitextra
        uses: liatrio/github-actions/git-extra@master
      - id: gitty-up
        uses: liatrio/github-actions/gitty-up@base-branch
        with:
          url: https://github.com/rode/charts.git
          base_branch: main
          username: ${{ github.actor }}
          password: ${{ secrets.GITTY_UP_TOKEN }}
          file: charts/grafeas-elasticsearch/values.yaml
          values: image.tag=${{steps.gitextra.outputs.version}}